# Generated by Django 5.0.1 on 2024-01-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_post',
            new_name='guest_can_pause',
        ),
    ]
